### ISSUE TITLE
Redirect output of Assert methods

### ISSUE THREAD

**Issue by dfch** [imfrancisd/PowerShell-Assert-Library#10]
Hi, I am thinking about using your `PowerShell-Assert-Library` in one of my script libraries, but am not happy with the way how the actual messages (upon assert failures) are generated. Is there a way to redirect the messages to something else (i.e. my custom event logger)?

In addition, why are you using `$PSCmdlet.WriteDebug` where the MSDN pages mentions not to use this method directly?

Thanks for your reply! Regards, Ronald

**Comment by imfrancisd** [comment]
Thanks Ronald!

Can you show me an example of how you would like to use the functions with your custom event logger?

I'm open to suggestions.

I use "$PSCmdlet.WriteDebug" because it avoids the situation where I might use a Write-Debug function created by someone else. I could use either "$PSCmdlet.WriteDebug" or "Microsoft.Powershell.Utility\Write-Debug", but I found that "$PSCmdlet.WriteDebug" was faster in PowerShell v4, so I went with that.

Thanks again for increasing the user count of this library by 100%. :-)

**Comment by imfrancisd** [comment]
I just looked at the MSDN documentation for PSCmdlet and I could not find any restrictions on the usage of PSCmdlet.WriteDebug.
- PSCmdlet Class
  - https://msdn.microsoft.com/en-us/library/system.management.automation.pscmdlet(v=vs.85).aspx
- PSCmdlet Members
  - https://msdn.microsoft.com/en-us/library/system.management.automation.pscmdlet_members(v=vs.85).aspx
- PSCmdlet Methods
  - https://msdn.microsoft.com/en-us/library/system.management.automation.pscmdlet_methods(v=vs.85).aspx
- Cmdlet.WriteDebug Method
  - https://msdn.microsoft.com/en-us/library/system.management.automation.cmdlet.writedebug(v=vs.85).aspx

Can you tell me where you found that restriction?

**Comment by dfch** [comment]
> I use "$PSCmdlet.WriteDebug" because it avoids the situation where I might use a Write-Debug function created by someone else.

This is exactly our use case - we want to redirect the output of the message. If you used `Write-Debug` I could re-define the Cmdlet and forward the message to our logging system quite easily.

I saw the remark of not using the method in [WriteDebugCommand](https://msdn.microsoft.com/en-us/library/microsoft.powershell.commands.writedebugcommand%28v=vs.85%29.aspx):

> The Write-Debug cmdlet class that is implemented by Windows PowerShell. This class is included in this SDK for completeness only. The members of this class cannot be used directly, nor should this class be used to derive other classes.

But maybe I am getting something wrong here.

I can imagine that the native class method is faster than the Cmdlet version. However, for testing this should not be a big deal in my opinion.

As we are a little bit under pressure in our project and our use case is a bit different altogether (we are testing our scripts in Pester but wanted to use the `Assert` method for runtime validation similar to [C# CodeContracts](http://research.microsoft.com/en-us/projects/contracts/userdoc.pdf)), I decided to reuse parts of your assert function (and gave credit according to your MIT license credit in our [NOTICE](https://github.com/dfch/biz.dfch.PS.System.Logging/blob/master/NOTICE) file). I hope this is ok for you.

Maybe your module could provide a means for a method overload via a module variable (a poor man's dependency injection). You could define `Write-Debug` as the default method so any user could overwrite it with a different method (as long the input parameters stay the same).

We use this in our modules in a similar way for different purposes and have a module configuration variable that can be changed at runtime. There you could define the place to override your logging implementation.

This is the example of how the logging variable of our [biz.dfch.PS.System.Logging](https://github.com/dfch/biz.dfch.PS.System.Logging) module looks like:

``` posh
PS > Get-Module biz.dfch.PS.System.Logging
ModuleType Name                       ExportedCommands
---------- ----                       ----------------
Script     biz.dfch.PS.System.Logging {Assert-IsTrue, Out-Message, Out-MessageAlert, Out-MessageCritical...}

PS > $biz_dfch_PS_System_Logging
Name                           Value
----                           -----
Log4NetLogger                  root
Log4NetConfigurationFile       C:\Program Files\WindowsPowerShell\Modules\biz.dfch.PS.System.Logging\Log4netConfiguration.xml
Logger                         log4net.Core.LogImpl
Severity                       {INFORMATIONAL, ERR, NOTICE, DBG...}
EventSource                    Default
DirectoryFormat                yyyy-MM
EventLogging                   False
Escalated                      log4net.Core.LogImpl
FileFormat                     yyyy-MM
Log4NetFileAppender            RollingLogFileAppender
DirectoryBase                  C:\Logs\biz.dfch.PS.System.Logging
FileLogging                    True
```

**Comment by imfrancisd** [comment]
> I decided to reuse parts of your assert function (and gave credit according to your MIT license credit in our NOTICE file). I hope this is ok for you.

Absolutely! Very ok with it.

**Comment by imfrancisd** [comment]
> This is exactly our use case - we want to redirect the output of the message. If you used  Write-Debug  I could re-define the Cmdlet and forward the message to our logging system quite easily.

Maybe I should do the same for verbose and error messages as well.

Let me study your module for a bit.

In the meantime, feel free to modify the functions in whatever way is useful to you. If you'd like to create a pull request later on, I'd gladly consider it.

**Comment by imfrancisd** [comment]
I think I'll just go ahead and call Write-Debug and Write-Verbose.

**Comment by imfrancisd** [comment]
I just updated the module. Let me know how it works out for you.

**Comment by dfch** [comment]
cool and thanks for the quick response! with these regular Cmdlets being used we can now easily do what we want and redirect the log to a target of our choice. thanks again!
